name: BookService CI/CD

on:
  push:
    paths:
      - 'book-service/**'  # Trigger on changes in the backend folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your region

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <your-ecr-repository-url>

      - name: Build Docker Image
        run: docker build -t <your-ecr-repository-url>:latest ./backend

      - name: Push Docker Image to ECR
        run: docker push <your-ecr-repository-url>:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster <your-cluster-name> \
            --service <your-service-name> \
            --force-new-deployment
